### PR TITLE
description of server/ path

### PR DESCRIPTION
**Pull request by cornelf**
* [x] Ready for review

### CODE REVIEW

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/4/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/4/
You have FAILED the short:test!

**Comment by cornelf** [comment]
build scala short

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/5/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/4/
long:test  SUCCESS. Nothing less expected!

**Comment by cornelf** [comment]
build scala short

**Comment by cornelf** [comment]
build scala long

**Comment by cornelf** [comment]
build ios

**Comment by cornelf** [comment]
build scala long

**Comment by cornelf** [comment]
build ios

**Comment by cornelf** [comment]
build scala short

**Comment by cornelf** [comment]
build scala short

**Comment by cornelf** [comment]
build scala long

**Comment by cornelf** [comment]
build scala long

**Comment by carlpulley** [comment]
build scala short

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
build scala short

**Pull request merged**
