### PR TITLE
Query model for exercise sessions

### PR DESCRIPTION
**Pull request by carlpulley**
* [x] defined query logic (based on dynamic linear-time logic)
* [x] defined query to state-machine compiler
* [x] implemented runtime monitoring callback interface (allows current state of query evaluation to interact with application/business logic driven queries)
* [x] refactoring of random exercise model
* [x] integration into existing Lift classifier code
* [x] implemented unit testing
* [x] `sbt test` passes
* [x] ready for review/merge

---
Issue [LIFT-36](https://cakesolutions.jira.com/browse/LIFT-36) tracks this PR.
Current PR still uses the random exercising model. Future PRs will:
* integrate SMT provers into the code base (e.g. via [Scala-Z3](https://github.com/epfl-lara/ScalaZ3) or [CVC4](http://cvc4.cs.nyu.edu/web/) - both support JNI APIs)
* introduce query state rewriting (to simplify state formulae generated during query evaluation over event traces)
* improve integration of classifiers into application logic (e.g. so that they may take full advantage of the classifications results).

### CODE REVIEW

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by carlpulley** [comment]
buildme

**Pull request merged**
