### PR TITLE
test pr 2 do not merge

### PR DESCRIPTION
**Pull request by cornelf**
* [x] do not merge!

### CODE REVIEW

**Comment by cornelf** [comment]
buildme

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/3/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/3/
You have FAILED the short:test!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/3/
You have FAILED the long:test!

**Pull request closed without merging**
