### PR TITLE
CVC4 Support for Lift

### PR DESCRIPTION
**Pull request by carlpulley**
* [x] added in CVC4 JNI jar file as unmanaged dependency
* [x] defined CVC4 satisfiability function
* [x] unit testing for CVC4 simplify, satisfiability and validity functions
* [ ] integration testing of `ExerciseModel.evaluate` function
* [x] `main` dockerfile updated to build CVC4 shared libraries
* [x] defined `Vagrantfile` for building development environment
* [ ] `sbt test`
* [ ] ready for review/merge

---
Issue [LIFT-36](https://cakesolutions.jira.com/browse/LIFT-36) tracks this PR.

This PR builds on ~~https://github.com/eigengo/lift/pull/58~~ by introducing an implementation of the `SMTInterface` based on the [CVC4](http://cvc4.cs.nyu.edu/web/) theorem prover.

A future PR will investigate possible viable implementations for the `SMTInterface.simplify` function via the CVC4 SMT function `simplify: Expr -> Expr` (for now, no rewriting occurs).

---
 **[Historical]** CVC4 Install Instructions (for OS X with brew 'support'):
```bash
wget http://cvc4.cs.nyu.edu/builds/src/cvc4-1.4.tar.gz
tar -xzvf cvc4-1.4.tar.gz
cd cvc4-1.4
brew install libantlr3c swig
./configure --prefix=/usr/local/Cellar/cvc4/1.4 --enable-language-bindings=java JAVA_CPPFLAGS=-I/System/Library/Frameworks/JavaVM.framework/Headers && make && make install && brew link cvc4
```
We expect the JNI shared library to be located at `/usr/local/Cellar/cvc4/1.4/lib/jni/libcvc4jni.dylib`

**Note:** the above instructions worked for myself on 1 machine - for the other two they failed!!

---
**[Default]** Instructions for building/testing within a vagrant environment (this is essentially our Docker container environment):
```bash
cd $LIFT_SERVER_ROOT
vagrant up
vagrant ssh
sbt test:compile # <== if akka-persistence-cassandra fails to download, simply run again!
sbt test
```

### CODE REVIEW

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
flowme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cornelf** [comment]
buildme

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/1/
You have FAILED the iOS!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/2/
You have FAILED the iOS!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/1/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/1/
long:test  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/3/
You have FAILED the iOS!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/4/
You have FAILED the iOS!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/2/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/2/
long:test  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/3/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/3/
long:test  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/5/
You have FAILED the iOS!

**Comment by lauraglasu** [comment]
build scala short

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/1/
short:test  SUCCESS! Nothing less expected!

**Comment by lauraglasu** [comment]
build scala long

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/1/
long:test  SUCCESS. Nothing less expected!

**Comment by lauraglasu** [comment]
build scala long

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/2/
long:test  SUCCESS. Nothing less expected!

**Comment by lauraglasu** [comment]
build ios

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/1/
You have FAILED the iOS!

**Comment by lauraglasu** [comment]
build ios

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/2/
You have FAILED the iOS!

**Comment by lauraglasu** [comment]
build ios

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/3/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/3/
long:test  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/2/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/4/
iOS  SUCCESS. Nothing less expected!

**Comment by lauraglasu** [comment]
build scala short

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/1/
short:test  SUCCESS! Nothing less expected!

**Comment by lauraglasu** [comment]
build ios

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/1/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/2/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/1/
long:test  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/2/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/1/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/1/
long:test  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/1/
You have FAILED the iOS!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/2/
short:test  SUCCESS! Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/2/
long:test  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/2/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/1/
You have FAILED the short:test!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/1/
You have FAILED the long:test!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/1/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-ios-pr/2/
iOS  SUCCESS. Nothing less expected!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-short-pr/2/
You have FAILED the short:test!

**Comment by cake-demo** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.cakedemo.eigengo.io//job/dev.build.lift-scala-long-pr/2/
You have FAILED the long:test!

**Pull request closed without merging**
